Topic4Assignment-EJB/src/beans/Order.java
package beans;

public class Order {
	String orderNo = "";
	String productName = "";
	float price = 0;
	int quantity = 0;
	
	public Order(String orderNo, String productName, float price, int quantity) {
		this.orderNo = orderNo;
		this.productName = productName;
		this.price = price;
		this.quantity = quantity;
	}

	public String getOrderNo() {
		return orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	public String getProductName() {
		return productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public float getPrice() {
		return price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public int getQuantity() {
		return quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}
	
}

Topic4Assignment-EJB/src/beans/User.java
//Noah Canepa
package beans;

import javax.faces.bean.ManagedBean;

@ManagedBean
public class User {
	private String firstName;
	private String lastName;
	
	public User() {
		firstName = "Peter";
		lastName = "Piper";
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
}

Topic4Assignment-EJB/src/controllers/FormController.java
//Noah Canepa
package controllers;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.inject.Inject;

import beans.User;
import business.MyTimerService;
import business.OrderBusinessInterface;

@ManagedBean
public class FormController {
	
	@Inject
	OrderBusinessInterface services;
	
	@EJB
	MyTimerService timer;
	
	public String onSubmit() {
		//retrieves user values
		FacesContext context = FacesContext.getCurrentInstance();
		User user = context.getApplication().evaluateExpressionGet(context, "#{user}", User.class);
		
		//prints message to console to tell which Business class is currently selected as an alternative
		services.test();
		
		//start a timer when login is clicked
		timer.setTimer(10000);
		
		//put user into Post request
		FacesContext.getCurrentInstance().getExternalContext().getRequestMap().put("user", user);
		//show next page
		return "Response.xhtml";
	}
	
	public OrderBusinessInterface getService() {
		return services;
	}
}

Topic4Assignment-EJB/WebContent/Response.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
      
		<head>
		<title><ui:insert name="pageTitle">Page Title</ui:insert></title>
		<style>
			.order-table {
			border:2px red solid;
			}
			.order-table-odd{
			background: #AAE;
			}
			.order-table-header{
			font-weight: bold;
			}
		</style>
		</head>

<body>
	<h1>Response Page</h1>
	<p>Hello #{user.firstName} #{user.lastName}, Your Orders Are</p>
	<h:dataTable value = "#{formController.service.orders}" var="o" styleClass = "order-table" 
	headerClass = "order-table-header" rowClasses = "order-table-odd, order-table-even">
		<h:column>
			<f:facet name ="header">Order Number</f:facet>
			#{o.orderNo}
		</h:column>
		<h:column>
			<f:facet name ="header">Product Name</f:facet>
			#{o.productName}
		</h:column>
		<h:column>
			<f:facet name ="header">Price</f:facet>
			#{o.price}
		</h:column>
		<h:column>
			<f:facet name ="header">Quantity</f:facet>
			#{o.quantity}
		</h:column>
	</h:dataTable>
</body>
		
</html>

Topic4Assignment-EJB/WebContent/layouts/commonContent.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
      <ui:composition>
      <h3> hur dur dur dur</h3>
      </ui:composition>	
</html>

Topic4Assignment-EJB/WebContent/layouts/commonFooter.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
      <ui:composition>
      	<h5>@Copyright Grand Canyon University</h5>
      </ui:composition>
</html>

Topic4Assignment-EJB/WebContent/layouts/commonHeader.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
      <ui:composition>
      	<h1>In Class Activity</h1>
      </ui:composition>
</html>

Topic4Assignment-EJB/WebContent/layouts/commonLayout.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
      <h:head>
      
      </h:head>
      <h:body>
      	<div id = "page">
      		<div id = "header">
      			<ui:insert name = "header">
      				<ui:include src="/layouts/commonHeader.xhtml" />
      			</ui:insert>
      		</div>
      		<div id ="content">
      			<ui:insert name = "content">
      				<ui:include src="/layouts/commonContent.xhtml" />
      			</ui:insert>
      		</div>
      		<div id = "footer">
      			<ui:insert name = "footer">
      				<ui:include src="/layouts/commonFooter.xhtml" />
      			</ui:insert>
      		</div>
      	</div>
      </h:body>
</html>

Topic4Assignment-EJB/WebContent/login-form.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
      
		<head>
		<title><ui:insert name="pageTitle">Page Title</ui:insert></title>
		</head>

<body>
	<ui:composition template = "/layouts/commonLayout.xhtml">
		<ui:define name = "content">
			<h:form>
				First Name: <h:inputText value="#{user.firstName}" />
				Last Name: <h:inputText value="#{user.lastName}" />
				<h:commandButton action="#{formController.onSubmit()}" value="Submit" />
			</h:form>
			<h:messages />
		</ui:define>
	</ui:composition>
</body>
		
</html>